services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./user-service:/app

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    expose:
      - "3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./product-service:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # internal message port (used by amqplib)
      - "15672:15672"   # management UI at http://localhost:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      -  nginx-conf:/etc/nginx/
    ports:
      - "8080:80"
    restart: unless-stopped

  consul-template:
      build:
        context: .
        dockerfile: consul-template.Dockerfile
      container_name: consul-template
      volumes:
        - ./nginx.ctmpl:/etc/consul-template/templates/nginx.ctmpl
        - nginx-conf:/etc/nginx/
      depends_on:
        - consul
      command: >
        -template "/etc/consul-template/templates/nginx.ctmpl:/etc/nginx/nginx.conf"
        -consul-addr="http://consul:8500"

volumes:
  # shared volume for consul-template and nginx
  nginx-conf:
